// @flow

// flow-typed signature: 347c2361efd4bb73ad6d7de9e51fff66
// flow-typed version: <<STUB>>/sha1_v1.x.x/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sha1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sha1' {
    declare module.exports: (str: string) => string;
}

/*
/!**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 *!/
declare module 'sha1/sha1' {
  declare module.exports: any;
}

declare module 'sha1/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sha1/sha1.js' {
  declare module.exports: $Exports<'sha1/sha1'>;
}
declare module 'sha1/test.js' {
  declare module.exports: $Exports<'sha1/test'>;
}
*/
